"""Static observer identity/mode pins submitted for independent review.

Only the thirty existing Constant sites reported by the generic D8 scanner
are bound to their exact owning AST, type/value and token spelling. Control
450, Worker451, Relay452, Gateway458 and existing broker socket principals
450/453 are inherited installed identities; 0o644 is existing plist/config
mode. No accounts, authority, runtime effects or file-wide exemption are added.
The unflagged broker SockPathMode432 (octal0o660) remains unmasked.

Source R4 SHA256 0c9711aed7695adc4928d91ea49ec67dd5f3edcc03d530f31b22a4c4d29b1b50.
R5 changes only _parse_service; all four owning ASTs here are unchanged.
These static data require independent source review, which is still pending.
Tests never generate or learn replacement pins from current source.
"""

REVIEWED_PATH = "control_plane/executive_release_observation.py"
REVIEWED_LITERAL_COUNT = 30
REVIEWED_ANCHORS = {'_SPECS': {'node_type': 'Assign',
            'ast_sha256': '9aa051823bd5797e1fa06dbb72e43ec9a1727c76eb208daecaa46b1b2bc9b63b',
            'sites': ((('value', 'elts', 0, 'args', 2), 'str', '_mastermind_exec', '"_mastermind_exec"'),
                      (('value', 'elts', 0, 'args', 3), 'str', '_mastermind_exec', '"_mastermind_exec"'),
                      (('value', 'elts', 0, 'args', 4), 'int', 450, '450'),
                      (('value', 'elts', 0, 'args', 6), 'int', 450, '450'),
                      (('value', 'elts', 1, 'args', 2), 'str', '_mastermind_worker', '"_mastermind_worker"'),
                      (('value', 'elts', 1, 'args', 3), 'str', '_mastermind_worker', '"_mastermind_worker"'),
                      (('value', 'elts', 1, 'args', 4), 'int', 451, '451'),
                      (('value', 'elts', 1, 'args', 6), 'int', 451, '451'),
                      (('value', 'elts', 2, 'args', 2),
                       'str',
                       '_mastermind_sol_relay',
                       '"_mastermind_sol_relay"'),
                      (('value', 'elts', 2, 'args', 3),
                       'str',
                       '_mastermind_sol_relay',
                       '"_mastermind_sol_relay"'),
                      (('value', 'elts', 2, 'args', 4), 'int', 452, '452'),
                      (('value', 'elts', 2, 'args', 6), 'int', 452, '452'),
                      (('value', 'elts', 3, 'args', 2),
                       'str',
                       '_mastermind_executive_mcp',
                       '"_mastermind_executive_mcp"'),
                      (('value', 'elts', 3, 'args', 3),
                       'str',
                       '_mastermind_executive_mcp',
                       '"_mastermind_executive_mcp"'),
                      (('value', 'elts', 3, 'args', 4), 'int', 458, '458'),
                      (('value', 'elts', 3, 'args', 7), 'int', 420, '0o644'))},
 '_config_join': {'node_type': 'FunctionDef',
                  'ast_sha256': '97bbb33bf9988360b37cc4acf8dd5227f6b9ea21ea881b65a5bbf8914c479454',
                  'sites': ((('body', 0, 'body', 0, 'value', 'values', 2, 'comparators', 0),
                             'int',
                             450,
                             '450'),
                            (('body',
                              0,
                              'orelse',
                              0,
                              'body',
                              0,
                              'value',
                              'values',
                              3,
                              'args',
                              0,
                              'generators',
                              0,
                              'iter',
                              'elts',
                              0,
                              'elts',
                              1),
                             'int',
                             451,
                             '451'),
                            (('body',
                              0,
                              'orelse',
                              0,
                              'body',
                              0,
                              'value',
                              'values',
                              3,
                              'args',
                              0,
                              'generators',
                              0,
                              'iter',
                              'elts',
                              1,
                              'elts',
                              1),
                             'int',
                             451,
                             '451'),
                            (('body',
                              0,
                              'orelse',
                              0,
                              'body',
                              0,
                              'value',
                              'values',
                              3,
                              'args',
                              0,
                              'generators',
                              0,
                              'iter',
                              'elts',
                              2,
                              'elts',
                              1),
                             'int',
                             450,
                             '450'),
                            (('body',
                              0,
                              'orelse',
                              0,
                              'orelse',
                              0,
                              'orelse',
                              0,
                              'body',
                              0,
                              'value',
                              'values',
                              3,
                              'comparators',
                              0),
                             'int',
                             458,
                             '458'))},
 '_content_snapshot': {'node_type': 'FunctionDef',
                       'ast_sha256': '2e0a948e28f526adfb3d4e99150251de3393738f0f14edc2a1f57a9d4f3f75d3',
                       'sites': ((('body', 1, 'body', 0, 'value', 'args', 2), 'int', 420, '0o644'),)},
 '_EXTRA_PROFILES': {'node_type': 'Assign',
                     'ast_sha256': '840ffc6b7fedb99d3ba794451fc71d32031a458026435d7d734549f058e104bc',
                     'sites': ((('value', 'values', 0, 'values', 8, 'values', 0, 'values', 1),
                                'int',
                                453,
                                '453'),
                               (('value', 'values', 0, 'values', 8, 'values', 0, 'values', 4),
                                'int',
                                450,
                                '450'),
                               (('value', 'values', 1, 'values', 3),
                                'str',
                                '_mastermind_sol_relay',
                                "'_mastermind_sol_relay'"),
                               (('value', 'values', 1, 'values', 14),
                                'str',
                                '_mastermind_sol_relay',
                                "'_mastermind_sol_relay'"),
                               (('value', 'values', 2, 'values', 3),
                                'str',
                                '_mastermind_worker',
                                "'_mastermind_worker'"),
                               (('value', 'values', 2, 'values', 11, 'values', 0, 'values', 1),
                                'int',
                                450,
                                '450'),
                               (('value', 'values', 2, 'values', 11, 'values', 0, 'values', 4),
                                'int',
                                450,
                                '450'),
                               (('value', 'values', 2, 'values', 16),
                                'str',
                                '_mastermind_worker',
                                "'_mastermind_worker'"))}}
