import { StrictMode, useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { MissionDocument, MissionRead, createSameOriginMissionRead, selectionFromLocation, unavailableMission, validateMission, type ListSection } from './mission'
import './styles.css'

type WorkCard={work_ref?:string;title?:string;state?:string;next_action?:string;autonomy?:{root_job_id?:string|null}}
declare global { interface Window { MastermindMissionHost?: { readMission?: MissionRead; selection?: { workRef: string; rootJobId?: string | null }; ccrNonce?: string; controlRoom?: {schema?:string; generated_at?:string; work?:WorkCard[]} } } }
const nav = ['Today', 'Programs', 'Mission Workspace', 'Connections', 'Evidence', 'Conversation'] as const
const text = (value: unknown, fallback = 'Not established') => typeof value === 'string' && value.length ? value : fallback
const status = (value: unknown) => text(value, 'UNKNOWN').replaceAll('_', ' ')

function State({ value }: { value: unknown }) { return <span className={`state state-${String(value ?? 'UNKNOWN').toLowerCase()}`}>{status(value)}</span> }
function ListState({ title, section }: { title: string; section: ListSection }) { return <section className="card"><div className="section-title"><h2>{title}</h2><State value={section.state} /></div><p className="muted">{section.reason_codes?.join(' · ') || (section.coverage === 'COMPLETE' ? 'Complete source coverage.' : 'Coverage is not established.')}</p>{section.items?.length ? <ul className="items">{section.items.map((item, i) => <li key={String(item.job_id ?? item.id ?? i)}><code>{text(item.job_id ?? item.id)}</code><span>{status(item.status ?? item.state)}</span><small>{text(item.orchestration_role ?? item.kind, 'No role projected')}</small></li>)}</ul> : <p className="empty">No items are rendered. This is not evidence of zero work.</p>}</section> }

function App() {
  const initial = useMemo(() => window.MastermindMissionHost?.selection ?? selectionFromLocation(), [])
  const hostWork = window.MastermindMissionHost?.controlRoom?.schema === 'mastermind.chairman_control_room.v1' ? (window.MastermindMissionHost.controlRoom.work ?? []).filter((w): w is WorkCard & {work_ref:string} => typeof w.work_ref === 'string') : []
  const [selection, setSelection] = useState(initial)
  const [active, setActive] = useState<(typeof nav)[number]>('Today')
  const [document, setDocument] = useState<MissionDocument>(() => unavailableMission(initial?.workRef, initial ? 'SOURCE_NOT_READ' : 'NO_HOST_SELECTION'))
  const [notice, setNotice] = useState('A qualified source has not been read.')
  const generation = useRef(0)
  const nativeShell = '__TAURI_INTERNALS__' in window
  useEffect(() => {
    if (nativeShell) {
      const current = ++generation.current
      setDocument(unavailableMission(selection?.workRef, 'NATIVE_TRANSPORT_UNCONFIGURED'))
      setNotice('Native shell detected. Its fixed transport is unconfigured; no same-origin service request was attempted.')
      import('@tauri-apps/api/core').then(({ invoke }) => invoke<{ build_identity: string; transport: string; state: string }>('readiness')).then(readiness => {
        if (generation.current === current) setNotice(`Native build ${readiness.build_identity}: ${readiness.transport} / ${readiness.state}. No service identity is configured.`)
      }).catch(() => { if (generation.current === current) setNotice('Native shell detected, but its fixed readiness receipt was unavailable. No source request was attempted.') })
      return
    }
    if (!selection) return
    const current = ++generation.current; const controller = new AbortController(); const read = window.MastermindMissionHost?.readMission ?? (window.MastermindMissionHost?.ccrNonce ? createSameOriginMissionRead(window.MastermindMissionHost.ccrNonce) : null)
    if (!read) { setDocument(unavailableMission(selection.workRef, 'QUALIFIED_HOST_READ_UNAVAILABLE')); setNotice('A qualified host read port or in-memory CCR nonce was not supplied.'); return }
    setNotice('Reading the selected mission from its fixed source…')
    read({ ...selection, signal: controller.signal }).then(result => { if (generation.current === current && validateMission(result, selection.workRef, selection.rootJobId)) { setDocument(result); setNotice('Source state is reported by the mission projection; rendering did not refresh it.') } else if (generation.current === current) { setDocument(unavailableMission(selection.workRef, 'SELECTION_OR_SCHEMA_MISMATCH')); setNotice('The response did not match the selected work and root identity.') } }).catch(() => { if (generation.current === current && !controller.signal.aborted) { setDocument(unavailableMission(selection.workRef, 'SOURCE_UNAVAILABLE')); setNotice('Mission source is unavailable. No mission, relationship, or conversation was fabricated.') } })
    return () => controller.abort()
  }, [selection, nativeShell])
  const d = document; const unavailable = d.read_state.state === 'UNAVAILABLE'
  const workspace=<><section className="hero"><div><span className="eyebrow">PROGRAM</span><h2>{text(d.program.work_ref)}</h2><p>{text(d.program.next_action, 'No next action was projected by the source.')}</p></div><div className="facts"><div><small>MISSION ROOT</small><code>{text(d.mission.root_job_id)}</code></div><div><small>RUNTIME ROOT STATE</small><State value={d.mission.runtime_root_state} /></div><div><small>EXECUTION</small><State value={d.execution.state} /></div></div></section><div className="grid"><section className="card"><div className="section-title"><h2>Mission</h2><State value={d.mission.status} /></div><dl><dt>Root job</dt><dd><code>{text(d.mission.root_job_id)}</code></dd><dt>Role</dt><dd>{text(d.mission.orchestration_role)}</dd><dt>Capability</dt><dd><State value={d.mission.capability?.state} /></dd><dt>Submission</dt><dd><State value={d.mission.submission_availability} /></dd></dl></section><section className="card"><div className="section-title"><h2>Principal</h2><State value={d.transport.dispatch_state} /></div><dl><dt>Accountable seat</dt><dd>{text(d.principal.accountable_seat)}</dd><dt>Current worker</dt><dd>{text(d.principal.current_worker)}</dd><dt>Owed turn</dt><dd>{text(d.principal.owed_turn)}</dd><dt>Transport</dt><dd>{text(d.transport.reason)}</dd></dl></section><section className="card"><div className="section-title"><h2>Review & acceptance</h2><State value={d.acceptance.state} /></div><dl><dt>Review verdict</dt><dd><State value={d.review.verdict} /></dd><dt>Posture</dt><dd><State value={d.posture.value} /></dd><dt>Rule</dt><dd>{text(d.posture.rule)}</dd></dl></section></div><ListState title="Mission tree" section={d.children} /></>
  const content=active==='Mission Workspace'?workspace:active==='Today'?<section className="card"><h2>Today</h2><p className="muted">{text(d.program.next_action,'No source-qualified next action is available.')}</p><p>Known mission subset: {d.children.items?.length ?? 0}; coverage: {status(d.children.coverage)}.</p></section>:active==='Programs'?<section className="card"><h2>Programs</h2>{hostWork.length?<div className="programs">{hostWork.map(w=><button key={w.work_ref} onClick={()=>{setSelection({workRef:w.work_ref,rootJobId:w.autonomy?.root_job_id});setActive('Mission Workspace')}}><b>{text(w.title,w.work_ref)}</b><span>{status(w.state)} · {text(w.next_action,'No next action projected')}</span></button>)}</div>:<p className="empty">No host-provided canonical control-room work list is available.</p>}</section>:active==='Connections'?<ListState title="Root and child relationships" section={d.children}/>:active==='Evidence'?<section className="card"><h2>Evidence</h2><p>Source generation: <code>{JSON.stringify(d.source?.source_generation ?? {})}</code></p><p>Control room source time: {text(d.source?.control_room_generated_at)}; fabric source time: {text(d.source?.fabric_view_generated_at)}.</p><p>Artifact summary present: {String(d.execution.summary_present ?? false)}; artifact references: {d.execution.artifacts?.length ?? 0}.</p></section>:<section className="card"><div className="section-title"><h2>Conversation</h2><State value={d.conversation.state}/></div><p className="muted">{d.conversation.reason_codes?.join(' · ') || 'The qualified reader has not been mounted by its owner.'}</p><p className="empty">No protected reader port, visible content, send, resume, or stop control is supplied here.</p></section>
  return <div className="shell"><a className="skip" href="#content">Skip to workspace</a><aside><div className="brand">▦ <span>MASTERMIND<small>OPERATING SYSTEM</small></span></div><nav aria-label="Workspace navigation">{nav.map(item => <button key={item} className={active === item ? 'active' : ''} onClick={() => setActive(item)}>{item}</button>)}</nav><div className="side-note"><b>Read-only workspace</b><br />Source, runtime, transport, and acceptance remain separate facts.</div></aside><main id="content" tabIndex={-1}><header><div><span className="eyebrow">{active}</span><h1>{d.program.title || 'Mission workspace'}</h1><p>{unavailable ? 'The source could not provide this mission.' : 'A bounded rendering of the selected mission projection.'}</p></div><State value={d.read_state.state} /></header><div className="notice" role="status">{notice}</div>{content}<section className="card"><h2>Missingness & source state</h2>{d.missingness?.length ? <ul className="missing">{d.missingness.map((m, i) => <li key={i}><State value={m.missingness_class} /> <code>{text(m.target_field)}</code> — {text(m.reason)}</li>)}</ul> : <p className="empty">No missingness facts were projected. This does not add a freshness claim.</p>}</section></main></div>
}
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
