"""Self-contained in-chat Control Room resource for the Steward app."""
from __future__ import annotations

UI_RESOURCE_URI = "ui://mastermind/steward/control-room-v1.html"
UI_MIME_TYPE = "text/html+skybridge"

CONTROL_ROOM_HTML = r"""<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
:root{color-scheme:dark;font-family:Inter,system-ui,sans-serif}body{margin:0;background:#090d14;color:#edf2f7}.wrap{padding:16px}.head{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}h1{font-size:16px;margin:0}.pill{padding:5px 9px;border:1px solid #334155;border-radius:999px;font-size:11px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:8px}.card{background:#111827;border:1px solid #263244;border-radius:10px;padding:10px}.key{font-size:10px;color:#94a3b8;text-transform:uppercase}.value{font-size:14px;font-weight:650;margin-top:5px;overflow-wrap:anywhere}.meta{font-size:10px;color:#94a3b8;margin-top:5px}.empty{padding:24px;border:1px dashed #334155;border-radius:10px;text-align:center;color:#94a3b8}</style></head><body><div class="wrap"><div class="head"><h1>Mastermind Control Room</h1><span id="state" class="pill">Awaiting data</span></div><div id="content" class="empty">Run a Mastermind Steward action to populate this view.</div></div><script>
(()=>{const c=document.getElementById('content'),s=document.getElementById('state');let latest=null;const esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));const short=v=>{v=String(v??'');return v.length>32?v.slice(0,16)+'…'+v.slice(-10):v};function render(){const p=latest&&latest.structuredContent?latest.structuredContent:latest,d=p&&p.data?p.data:p,f=Array.isArray(d&&d.facts)?d.facts:[];s.textContent=(d&&d.state)||(p&&p.ok===false?'REFUSED':'UNKNOWN');if(!f.length){c.className='empty';c.textContent='No structured facts returned.';return}c.className='grid';c.innerHTML=f.map(x=>{const src=Array.isArray(x.sources)&&x.sources[0]?x.sources[0]:{};return `<article class="card"><div class="key">${esc(x.predicate)}</div><div class="value">${esc(x.value)}</div><div class="meta">${esc(short(x.subject_ref))} · ${esc(x.freshness||'UNKNOWN')}</div><div class="meta">${esc(src.owner||'unknown')} · ${esc(short(src.source_ref))}</div></article>`}).join('')}function read(){const o=window.openai||{};latest=o.toolOutput||o.structuredContent||latest;render()}window.addEventListener('openai:set_globals',e=>{latest=e.detail&&e.detail.globals&&(e.detail.globals.toolOutput||e.detail.globals.structuredContent)||latest;render()});read();setTimeout(read,250)})();
</script></body></html>"""

__all__ = ["CONTROL_ROOM_HTML", "UI_MIME_TYPE", "UI_RESOURCE_URI"]
