"""Stable, SDK-free contracts for the Mastermind company-dialogue MCP facade."""

from integrations.mastermind_company_mcp.adapter import (
    CompanyDialogueGateway,
    DialogueBinding,
    DialogueBindingResolver,
)
from integrations.mastermind_company_mcp.consultation import (
    COMPANY_CONSULTATION_CAPABILITY,
    COMPANY_CONSULTATION_ERROR_CODES,
    COMPANY_CONSULTATION_RESULT_SCHEMA,
    COMPANY_CONSULTATION_SERVER_IDENTITY,
    COMPANY_CONSULTATION_SERVER_NAME,
    COMPANY_CONSULTATION_SERVER_VERSION,
    COMPANY_CONSULTATION_TOOL_SCHEMA_DIGEST,
    COMPANY_CONSULTATION_TOOL_SPECS,
    CompanyConsultationGateway,
    CompanyConsultationToolError,
    CompanyConsultationToolSpec,
    validate_company_consultation_tool_arguments,
)
from integrations.mastermind_company_mcp.schemas import (
    RESULT_SCHEMA,
    SCHEMA_SNAPSHOT_SHA256,
    SERVER_IDENTITY,
    SERVER_NAME,
    SERVER_VERSION,
    TOOL_SCHEMA_DIGEST,
    TOOL_SPECS,
    GatewayError,
    ToolSpec,
    error_envelope,
    result_envelope,
    schema_snapshot_sha256,
    tool_schema_digest,
    tool_schema_snapshot,
    validate_tool_arguments,
)

__all__ = [
    "COMPANY_CONSULTATION_CAPABILITY",
    "COMPANY_CONSULTATION_ERROR_CODES",
    "COMPANY_CONSULTATION_RESULT_SCHEMA",
    "COMPANY_CONSULTATION_SERVER_IDENTITY",
    "COMPANY_CONSULTATION_SERVER_NAME",
    "COMPANY_CONSULTATION_SERVER_VERSION",
    "COMPANY_CONSULTATION_TOOL_SCHEMA_DIGEST",
    "COMPANY_CONSULTATION_TOOL_SPECS",
    "CompanyDialogueGateway",
    "CompanyConsultationGateway",
    "CompanyConsultationToolError",
    "CompanyConsultationToolSpec",
    "DialogueBinding",
    "DialogueBindingResolver",
    "GatewayError",
    "RESULT_SCHEMA",
    "SCHEMA_SNAPSHOT_SHA256",
    "SERVER_IDENTITY",
    "SERVER_NAME",
    "SERVER_VERSION",
    "TOOL_SCHEMA_DIGEST",
    "TOOL_SPECS",
    "ToolSpec",
    "error_envelope",
    "result_envelope",
    "schema_snapshot_sha256",
    "tool_schema_digest",
    "tool_schema_snapshot",
    "validate_tool_arguments",
    "validate_company_consultation_tool_arguments",
]
