"""Active-Session Dialogue integration boundaries."""

from integrations.slack_agent_dialogue.contract import (
    AUTHORITY_CLASSES,
    ERROR_CODES as CONTRACT_ERROR_CODES,
    FABLE_MESSAGE_TYPES,
    MAX_FRAME_BYTES,
    MESSAGE_DISCRIMINATOR,
    MESSAGE_SCHEMA,
    MESSAGE_TYPES,
    PARENT_DISCRIMINATOR,
    PARENT_SCHEMA,
    SOL_MESSAGE_TYPES,
    DialogueContractError,
    adjudicate_reply,
    build_message,
    build_parent,
    parse_message_frame,
    parse_parent_frame,
    render_message,
    render_parent,
    semantic_fingerprint,
    validate_message,
    validate_parent,
)
from integrations.slack_agent_dialogue.engine import (
    ERROR_CODES as ENGINE_ERROR_CODES,
    BoundThread,
    DialogueContext,
    DialogueEngine,
    DialogueEngineError,
    DialoguePolicy,
    HistoryPage,
    MessageReceipt,
    ReadMessage,
    SlackDialogueClient,
    SlackEffectUnknown,
    SlackMessage,
    SlackTransportUnavailable,
    ThreadRead,
)
from integrations.slack_agent_dialogue.metadata_verifier import (
    ERROR_CODES as METADATA_ERROR_CODES,
    HttpResult,
    MetadataExpectation,
    MetadataVerificationError,
    RECEIPT_SCHEMA,
    SLACK_AUTH_TEST_URL,
    SlackAuthTestTransport,
    UrllibSlackAuthTestTransport,
    assert_secret_surfaces_clean,
    read_token_from_stdin,
    run,
    validate_expectation,
    verify_metadata,
)
from integrations.slack_agent_dialogue.service import (
    ERROR_CODES as SERVICE_ERROR_CODES,
    AgentDialogueService,
    CONTROL_VERSION,
    DialogueServiceError,
    ServiceConfig,
    call_service,
)

# Backward-compatible metadata-verifier name from the A0 recovery slice.
ERROR_CODES = METADATA_ERROR_CODES

__all__ = [
    "AUTHORITY_CLASSES",
    "AgentDialogueService",
    "BoundThread",
    "CONTRACT_ERROR_CODES",
    "CONTROL_VERSION",
    "DialogueContext",
    "DialogueContractError",
    "DialogueEngine",
    "DialogueEngineError",
    "DialoguePolicy",
    "DialogueServiceError",
    "ENGINE_ERROR_CODES",
    "ERROR_CODES",
    "FABLE_MESSAGE_TYPES",
    "HistoryPage",
    "HttpResult",
    "MAX_FRAME_BYTES",
    "MESSAGE_DISCRIMINATOR",
    "MESSAGE_SCHEMA",
    "MESSAGE_TYPES",
    "METADATA_ERROR_CODES",
    "MessageReceipt",
    "MetadataExpectation",
    "MetadataVerificationError",
    "PARENT_DISCRIMINATOR",
    "PARENT_SCHEMA",
    "RECEIPT_SCHEMA",
    "ReadMessage",
    "SERVICE_ERROR_CODES",
    "SLACK_AUTH_TEST_URL",
    "SOL_MESSAGE_TYPES",
    "ServiceConfig",
    "SlackAuthTestTransport",
    "SlackDialogueClient",
    "SlackEffectUnknown",
    "SlackMessage",
    "SlackTransportUnavailable",
    "ThreadRead",
    "UrllibSlackAuthTestTransport",
    "adjudicate_reply",
    "assert_secret_surfaces_clean",
    "build_message",
    "build_parent",
    "call_service",
    "parse_message_frame",
    "parse_parent_frame",
    "read_token_from_stdin",
    "render_message",
    "render_parent",
    "run",
    "semantic_fingerprint",
    "validate_expectation",
    "validate_message",
    "validate_parent",
    "verify_metadata",
]
