"""Compatibility aliases for neutral Agent Dialogue semantics."""
from common.agent_dialogue_turn_watcher import (
    ATTENTION_SCHEMA,
    ATTENTION_SOURCE_KIND,
    ATTENTION_WAKE_KIND,
    AgentDialogueAttention,
    Any,
    DialogueContractError,
    Enum,
    MESSAGE_SCHEMA_V2,
    Mapping,
    PARENT_SCHEMA_V2,
    Sequence,
    TURN_WATCH_MODE_V1,
    TurnAction,
    TurnDecision,
    TurnRoutingFacts,
    __all__,
    _canonical_identity,
    annotations,
    classify_turn,
    dataclass,
    hashlib,
    json,
    validate_message_v2,
    validate_parent_v2,
)
