"""control_plane.flags — enumerate MASTERMIND_* environment variables.

``enumerate_flags()`` returns a dict of every ``MASTERMIND_*`` env var
currently set in ``os.environ``, mapping name → value (str).

KNOWN_FLAGS
-----------
This list was generated by grepping the codebase for ``os.environ`` reads of
``MASTERMIND_*`` flags on 2026-07-05.

MAINTAINERS: after adding a new MASTERMIND_* flag anywhere in the codebase,
re-run ``scripts/system_census.py`` (MW1 deliverable) to regenerate this list
and update it here.  The list is used both as documentation and as the
canonical set of "known flags" for health-check diffs (new flag in env but not
in KNOWN_FLAGS → advisory event; expected flag absent → informational).
"""
from __future__ import annotations

import os

# ---------------------------------------------------------------------------
# Known flags — grep-derived, hardcoded for zero-import-time overhead.
# Source: grep -rn "MASTERMIND_" <repo> --include="*.py" | grep -oP "MASTERMIND_[A-Z_]+" | sort -u
# Date:   2026-07-05
# ---------------------------------------------------------------------------

KNOWN_FLAGS: list[str] = [
    # Auth / deployment
    "MASTERMIND_JOBSTORE",
    "MASTERMIND_AUTH_TOKEN",
    "MASTERMIND_COOKIE_SECURE",
    "MASTERMIND_PASSWORD",
    "MASTERMIND_REQUIRE_AUTH",
    "MASTERMIND_SERVE_ONLY",
    "MASTERMIND_SESSION_DAYS",
    "MASTERMIND_VPS_AUTHORITATIVE",
    # Bot / phase2
    "MASTERMIND_FAST_DERISK",
    "MASTERMIND_FLAGSHIP_JUDGMENT",
    "MASTERMIND_MACRO_RISK",
    "MASTERMIND_RISK_OFFICER",
    "MASTERMIND_TIMING_GATE",
    # Brain modules
    "MASTERMIND_COMMITTEE",
    "MASTERMIND_DWELL",
    "MASTERMIND_GATE_OFFICER",
    "MASTERMIND_NW_CONTEXT",
    "MASTERMIND_POSTURE_DECIDER",
    "MASTERMIND_REPUTATION_WEIGHTING",
    "MASTERMIND_RESEARCH_LLM",
    "MASTERMIND_RISK_GOVERNOR",
    "MASTERMIND_SELF_MIRROR",
    "MASTERMIND_SELF_TUNE",
    "MASTERMIND_STUDENT",
    "MASTERMIND_TECHNICIAN",        # dark seat: entry-timing TECHNICIAN (brain/technician.py), default OFF
    "MASTERMIND_DESK_QUORUM",       # dark ladder off|shadow|enforce: admit the TECHNICIAN seat into the buy gate, default off
    # Neural Web / P2 candidacy funnel (dark — additive buy-source, arm on a statistical bar, roadmap E8)
    "MASTERMIND_NW_DECISION",       # enum off|shadow|candidacy|shrink|vote (default off)
    "MASTERMIND_ROTATION_IN",       # enum off|watch|starter (default off)
    "MASTERMIND_DIVERGENCE_CLUE",   # bool 0|1 (default 0)
    "MASTERMIND_UNIVERSE_TRIAGE",   # bool 0|1 (default 0)
    # Buy-board LEARNING loop (dark — standout candidacy gate_go fix + proven-edge trust multiplier)
    "MASTERMIND_STANDOUT_UNGATED",  # bool 0|1 (default 0): admit gate_go=false board names as candidacy
    "MASTERMIND_BOARD_LEARNING",    # bool 0|1 (default 0): shrink standout scores by the board's forward edge
    "MASTERMIND_TREASURY_CONTEXT",
    # Mastermind AI self-improvement loop (W-AI — observational, files-only; no book authority)
    "MASTERMIND_AI_LOOP",           # bool, default ON: the nightly reflection/loop-log cycle
    "MASTERMIND_AI_REVIEW_LLM",     # bool, default OFF: capability gate for LLM prose on reviews
    # Portfolio / sizing
    "MASTERMIND_ALLOW_FRACTIONAL",
    "MASTERMIND_CAUTION_GROSS",
    "MASTERMIND_CAUTION_SCORE",
    "MASTERMIND_CHAIN_CAP",
    "MASTERMIND_DERISK_THEME_DROP",
    "MASTERMIND_EXPLORE_EPS",
    "MASTERMIND_EXPLORE_WEIGHT",
    "MASTERMIND_FIRM_CAPS",
    "MASTERMIND_FIRM_CLUSTER_CAP",
    "MASTERMIND_FIRM_NAME_CAP",
    "MASTERMIND_HW_FIRM_UNIVERSE",
    "MASTERMIND_HW_MIN_FUNDABLE",
    "MASTERMIND_MIN_POSITION_FRAC",
    "MASTERMIND_MIN_TRADE_FRAC",
    "MASTERMIND_NIGHTLY_USD_CAP",
    "MASTERMIND_NO_TRADE_BAND_FRAC",
    "MASTERMIND_POSTURE_ADAPT",
    "MASTERMIND_RISKOFF_GROSS",
    "MASTERMIND_RISKOFF_SCORE",
    "MASTERMIND_SELECTION_EXPLORE",
    # Packet gate
    "MASTERMIND_PACKET_GATE",
    # Version / program references (found in doc comments / grep, not runtime reads)
    "MASTERMIND_BRIDGE_PROGRAM",
    "MASTERMIND_CHARTER_V",
    "MASTERMIND_CONTROL_PLANE_MASTERPLAN",
    "MASTERMIND_FIX_MASTERPLAN",
    "MASTERMIND_LEARNING_DESIGN",
    "MASTERMIND_V",
]


# ---------------------------------------------------------------------------
# public API
# ---------------------------------------------------------------------------

# Flags whose VALUES are secrets. enumerate_flags() output lands in
# data/governance/run_events.jsonl (every run record) and the census —
# credential values must never reach a ledger, only the fact they are set.
_SECRET_MARKERS = ("PASSWORD", "TOKEN", "SECRET", "KEY", "PASS")


def enumerate_flags() -> dict[str, str]:
    """Return every MASTERMIND_* env var currently set.

    Returns
    -------
    dict[str, str]
        ``{flag_name: value}`` for all ``MASTERMIND_*`` keys in ``os.environ``.
        Secret-bearing flags (name contains PASSWORD/TOKEN/SECRET/KEY/PASS)
        report the literal string ``"<set>"`` instead of their value.
        Flags in ``KNOWN_FLAGS`` that are absent from the environment are NOT
        included (absence is informational, not an error at enumeration time).
    """
    return {
        k: ("<set>" if any(m in k for m in _SECRET_MARKERS) else v)
        for k, v in os.environ.items()
        if k.startswith("MASTERMIND_")
    }
